### ISSUE TITLE
[BugFix] 소비기록의 UITableView의 무너짐

### ISSUE THREAD

**Issue by jayn2u** [BudgetBuddiesTeam/iOS#54]
# 🍎 빈주머니즈 iOS 버그 수정

## 💡 Description

> 해야 할 업무에 대해서 설명해주세요!

- 스크린샷에 있는 것과 같이 `UITableView`의 View가 무너진 모습을 알 수 있습니다.
- 무너진 View를 다시 살리는 작업을 해야 합니다.

## ✅ To Do List

- [x] **ConsumedHistoryView** & **ConsumedHistoryViewController** 클래스 디버깅.

## 📝 ETC

> 기타 설명이 필요하다면 작성해주세요!

- 스크린샷을 첨부합니다.

<img width="559" alt="Screenshot 2024-08-03 at 16 50 00" src="https://github.com/user-attachments/assets/f13e9af8-f07b-4f20-b367-8bb970cfe814">

**Comment by jayn2u** [comment]
@SeungEEE 님 & @SeungWon1125 님 중에서 이런 문제 보신 적 있나요??

**Comment by SeungWon1125** [comment]
방금 확인해봤는데, 저도 비슷한 오류가 난 적이 있습니다.
예를 들어 UITableViewDataSource에서 셀을 10개 리턴하게 되어있는데
등록된 셀을 몇몇 셀에서만 사용하게 되면, 나머지 셀이 깨지고, 스크롤 또는 터치하면 원래대로 돌아오고 그랬던 적이 있습니다만,,
같은 오류인지는 모르겠네요..!!ㅜㅠ

**Comment by jayn2u** [comment]
> 방금 확인해봤는데, 저도 비슷한 오류가 난 적이 있습니다.
> 
> 예를 들어 UITableViewDataSource에서 셀을 10개 리턴하게 되어있는데
> 
> 등록된 셀을 몇몇 셀에서만 사용하게 되면, 나머지 셀이 깨지고, 스크롤 또는 터치하면 원래대로 돌아오고 그랬던 적이 있습니다만,,
> 
> 같은 오류인지는 모르겠네요..!!ㅜㅠ

맞아요. 저도 그렇게 하면 문제가 없더라구요??
그리고 정확한 건 아닌데, 이 문제는 시뮬레이터말고 실제 디바이스로 하면 괜찮게 된다고 하더라구요. 그래서 실제 디바이스에 빌드해봐야겠어요.

**Comment by jayn2u** [comment]
# 공지

- #89 에 해당 문제 해결해서 PR을 발송했습니다.
