### ISSUE TITLE
[BugFix] NavigationBar 색상과 View의 배경색의 차이 문제 해결

### ISSUE THREAD

**Issue by jayn2u** [BudgetBuddiesTeam/iOS#80]
# 🍎 빈주머니즈 iOS 버그 수정

## 💡 Description

> 해야 할 업무에 대해서 설명해주세요!

- NavigationBar 색상과 View의 배경색의 차이 문제 해결

## ✅ To Do List

- [ ] 해당 문제 해결

## 📝 ETC

> 기타 설명이 필요하다면 작성해주세요!

![Screenshot 2024-08-11 at 16 08 29](https://github.com/user-attachments/assets/c858f1bf-ef80-47bd-b831-ac171af9069d)

**Comment by SeungWon1125** [comment]
이것도 UI/UX 통일하면서 제가 작업할게용
