### ISSUE TITLE
[BugFix] NavigationBar의 BackButton 설계

### ISSUE THREAD

**Issue by jayn2u** [BudgetBuddiesTeam/iOS#82]
# 🍎 빈주머니즈 iOS 버그 수정

## 💡 Description

> 해야 할 업무에 대해서 설명해주세요!

- 네비게이션으로 연결된 ViewController에서 백버튼이 기본 BackButton으로 활성화 되어 있는 화면을 목격했어요!
- 해당 부분도 확인 후 재설계 해주시면 감사하겠습니다.

## ✅ To Do List

- [ ] 상위 NavigationController에 영향을 미치지 않는지 확인하며 BackButton 재설계

## 📝 ETC

> 기타 설명이 필요하다면 작성해주세요!

**Comment by SeungWon1125** [comment]
지금 승진님 휴가 중이시니까 제가 UI 개선하면서 모든 뷰 네비게이션바도 통일해서 PR 올릴게요!
